#ifndef __STORMLIBX_NET_PERF_H__
#define __STORMLIBX_NET_PERF_H__

#include <cstdint>

#define SNET_PERFID_TURN 1
#define SNET_PERFID_TURNSSENT 4
#define SNET_PERFID_TURNSRECV 5
#define SNET_PERFID_MSGSENT 6
#define SNET_PERFID_MSGRECV 7
#define SNET_PERFID_USERBYTESSENT 8
#define SNET_PERFID_USERBYTESRECV 9
#define SNET_PERFID_TOTALBYTESSENT 10
#define SNET_PERFID_TOTALBYTESRECV 11
#define SNET_PERFID_PKTSENTONWIRE 12
#define SNET_PERFID_PKTRECVONWIRE 13
#define SNET_PERFID_BYTESSENTONWIRE 14
#define SNET_PERFID_BYTESRECVONWIRE 15
#define SNET_PERFIDNUM 16

#define SNET_PERFTYPE_COUNTER 0x10410400
#define SNET_PERFTYPE_RAWCOUNT 0x00010000

void PerfAdd(uint32_t id, int32_t value);
void PerfIncrement(uint32_t id);
void PerfSet(uint32_t id, int32_t value);

#endif
